import { chromium } from 'playwright';
import sharp from 'sharp';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';

const output = new URL('../../output/ocean-qa/', import.meta.url);
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const results = { errors: [], checks: [] };
const capture = async (page, name) => page.screenshot({ path: new URL(name, output).pathname.replace(/^\/(\w:)/, '$1') });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1 });
  page.on('pageerror', error => results.errors.push(error.message));
  await page.goto('http://127.0.0.1:4187/ocean/index.html');
  await page.waitForFunction(() => document.querySelectorAll('.letter-image').length === 9);
  assert.equal(await page.locator('.letter-flip').count(), 9);
  await capture(page, 'desktop-home.png');
  const letter = page.locator('.letter-flip').first();
  await letter.hover();
  await page.waitForTimeout(750);
  assert.equal(await letter.getAttribute('aria-pressed'), 'true');
  await capture(page, 'desktop-flip.png');
  await page.mouse.move(4, 500);
  await page.waitForTimeout(750);
  await letter.focus();
  await page.keyboard.press('Space');
  assert.equal(await letter.getAttribute('aria-pressed'), 'true');
  await page.keyboard.press('Escape');
  assert.equal(await letter.getAttribute('aria-pressed'), 'false');
  results.checks.push('nine images, hover/keyboard flip');
  await page.locator('#primary-nav a[href="#internship"]').click();
  await page.waitForTimeout(1200);
  await capture(page, 'desktop-internship.png');
  const mediaPixels = await page.locator('.experience-media').first().screenshot();
  const mediaStats = await sharp(mediaPixels).stats();
  assert.ok(mediaStats.channels[2].mean > mediaStats.channels[0].mean + 50, 'global surfaces retain blue color');
  const media = page.locator('.experience-media').first();
  const bounds = await media.boundingBox();
  const globalBefore = await page.screenshot();
  await page.mouse.move(bounds.x + bounds.width / 2, bounds.y + bounds.height / 2);
  await page.mouse.move(bounds.x + 8, bounds.y + 12, { steps: 18 });
  await page.waitForTimeout(100);
  await capture(page, 'desktop-global-hover.png');
  assert.notDeepEqual(globalBefore, await page.screenshot(), 'global pointer response changes pixels');
  await page.locator('#primary-nav a[href="#projects"]').click();
  await page.waitForTimeout(11000);
  await capture(page, 'desktop-projects.png');
  const frame = page.frames().find(frame => frame.url().includes('/ice/index.html'));
  assert.ok(frame, 'local carousel frame');
  const canvas = frame.locator('canvas');
  assert.equal(await canvas.count(), 1);
  const pixels = await canvas.screenshot();
  const stats = await sharp(pixels).stats();
  assert.ok(stats.channels[0].stdev > 15, 'carousel canvas contains visible geometry');
  await page.locator('[data-project-select="2"]').click();
  await page.waitForTimeout(1400);
  assert.equal(await page.locator('[data-project-current]').textContent(), '03');
  const before = await canvas.screenshot();
  const c = await canvas.boundingBox();
  await page.mouse.move(c.x + c.width * .7, c.y + c.height * .5);
  await page.mouse.move(c.x + c.width * .66, c.y + c.height * .4, { steps: 20 });
  await page.waitForTimeout(120);
  const after = await canvas.screenshot();
  assert.notDeepEqual(before, after, 'source hover changes canvas pixels');
  results.checks.push('nonblank local canvas, project selection and live hover');
  await canvas.click({ position: { x: c.width * .65, y: c.height * .5 } });
  await page.waitForURL('**/project.html?id=03');
  assert.equal(await page.locator('h1 [data-project-number]').textContent(), '03');
  await page.locator('.detail-back').click();
  await page.waitForURL('**/index.html#projects');
  assert.equal(await page.locator('[data-project-current]').textContent(), '03');
  await page.locator('[data-project-view="list"]').click();
  assert.equal(await page.locator('.project-entry:visible').count(), 5);
  await page.locator('[data-project-view="gallery"]').click();
  await page.locator('[data-motion-toggle]').click();
  assert.equal(await page.locator('html').getAttribute('data-motion'), 'paused');
  await page.locator('[data-project-select="2"]').click();
  const pausedFrame = page.frames().find(frame => frame.url().includes('/ice/index.html'));
  await page.waitForTimeout(300);
  const pausedBefore = await pausedFrame.locator('canvas').screenshot();
  await page.waitForTimeout(300);
  assert.deepEqual(pausedBefore, await pausedFrame.locator('canvas').screenshot(), 'paused canvas is stable');
  results.checks.push('detail/back identity, five-item directory, motion pause');
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  mobile.on('pageerror', error => results.errors.push(error.message));
  await mobile.goto('http://127.0.0.1:4187/ocean/index.html');
  await mobile.waitForFunction(() => document.querySelectorAll('.letter-image').length === 9);
  await capture(mobile, 'mobile-home.png');
  assert.ok(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'no mobile horizontal overflow');
  await mobile.locator('.letter-flip').first().tap();
  assert.equal(await mobile.locator('.letter-flip').first().getAttribute('aria-pressed'), 'true');
  await mobile.locator('[data-menu-toggle]').tap();
  await mobile.locator('#primary-nav a[href="#projects"]').tap();
  await mobile.waitForTimeout(11000);
  await capture(mobile, 'mobile-projects.png');
  assert.equal(await mobile.locator('[data-menu-toggle]').getAttribute('aria-expanded'), 'false');
  assert.ok(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'project section fits mobile');
  results.checks.push('390px layout, touch flip and mobile anchor menu');
  const reduced = await browser.newPage({ viewport: { width: 1024, height: 768 }, reducedMotion: 'reduce' });
  reduced.on('pageerror', error => results.errors.push(error.message));
  await reduced.goto('http://127.0.0.1:4187/ocean/index.html#projects');
  await reduced.waitForTimeout(2500);
  assert.equal(await reduced.locator('html').getAttribute('data-motion'), 'paused');
  await reduced.locator('[data-project-next]').click();
  assert.equal(await reduced.locator('[data-project-current]').textContent(), '02');
  const reducedFrame = reduced.frames().find(frame => frame.url().includes('/ice/index.html'));
  const reducedCanvas = reducedFrame.locator('canvas');
  const reducedStats = await sharp(await reducedCanvas.screenshot()).stats();
  assert.ok(reducedStats.channels[0].stdev > 15, 'reduced-motion carousel remains visible');
  await capture(reduced, 'reduced-motion.png');
  results.checks.push('reduced motion preserves project navigation');
  assert.deepEqual(results.errors, []);
  console.log(JSON.stringify(results, null, 2));
} finally {
  await writeFile(new URL('results.json', output), JSON.stringify(results, null, 2));
  await browser.close();
}
